# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "_site/uploads" # Folder where user uploaded files should go
public_folder: "/uploads"

collections: # A list of collections the CMS should be able to edit
  # PAGES
  - name: "page"
    label: "Page"
    folder: "pages"
    editor:
      preview: false
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Title (voor in menu)", name: "title", widget: "string"}
      - {label: "Title tag (belangrijk voor google)", name: "title-tag", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Grote foto bovenaan", name: "hero-image", widget: "image", required: false}
      - {label: "Tekst over de grote foto heen", name: "hero-slogan", widget: "string", required: false}
      - {label: "In menu tonen?", name: "include-in-menu", widget: "boolean"}
      - {label: "In 'LEES OOK' lijstje tonen?", name: "include-in-other-pages-list", widget: "boolean"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
